Lombiq/src/Orchard.Web/Modules/Orchard.Packaging/Controllers/GalleryUpdatesController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Orchard.DisplayManagement;
using Orchard.Environment.Configuration;
using Orchard.Environment.Extensions;
using Orchard.Environment.Extensions.Models;
using Orchard.Localization;
using Orchard.Logging;
using Orchard.Mvc.Extensions;
using Orchard.Packaging.Models;
using Orchard.Packaging.Services;
using Orchard.Packaging.ViewModels;
using Orchard.Reports.Services;
using Orchard.Security;
using Orchard.Themes;
using Orchard.UI.Admin;
using Orchard.UI.Navigation;
using Orchard.UI.Notify;

namespace Orchard.Packaging.Controllers {
    [OrchardFeature("Gallery.Updates")]
    [Themed, Admin]
    public class GalleryUpdatesController : Controller {
        private readonly ShellSettings _shellSettings;
        private readonly IPackagingSourceManager _packagingSourceManager;
        private readonly IPackageUpdateService _packageUpdateService;
        private readonly IBackgroundPackageUpdateStatus _backgroundPackageUpdateStatus;

        public GalleryUpdatesController(
            ShellSettings shellSettings,
            IOrchardServices services,
            IPackagingSourceManager packagingSourceManager,
            INotifier notifier,
            IPackageUpdateService packageUpdateService,
            IBackgroundPackageUpdateStatus backgroundPackageUpdateStatus,
            IReportsCoordinator reportsCoordinator,
            IReportsManager reportsManager,
            IShapeFactory shapeFactory) {

            _shellSettings = shellSettings;
            _packagingSourceManager = packagingSourceManager;
            _packageUpdateService = packageUpdateService;
            _backgroundPackageUpdateStatus = backgroundPackageUpdateStatus;

            Services = services;
            Shape = shapeFactory;
            PackageUpdateService = packageUpdateService;

            T = NullLocalizer.Instance;
            Logger = NullLogger.Instance;
        }

        public IOrchardServices Services { get; private set; }
        public Localizer T { get; set; }
        public ILogger Logger { get; set; }
        public dynamic Shape { get; set; }
        public IPackageUpdateService PackageUpdateService { get; set; }

        public ActionResult ThemesUpdates(int? reportId, PagerParameters pagerParameters) {
            return PackageUpdate("ThemesUpdates", DefaultExtensionTypes.Theme, reportId, pagerParameters);
        }

        public ActionResult ModulesUpdates(int? reportId, PagerParameters pagerParameters) {
            return PackageUpdate("ModulesUpdates", DefaultExtensionTypes.Module, reportId, pagerParameters);
        }

        public ActionResult ReloadUpdates(string returnUrl) {
            _packageUpdateService.TriggerRefresh();
            _backgroundPackageUpdateStatus.Value = null;

            Services.Notifier.Warning(T("The feed has been notified for update. It might take a few minutes before the updates are displayed."));

            return this.RedirectLocal(returnUrl);
        }

        private ActionResult PackageUpdate(string view, string extensionType, int? reportId, PagerParameters pagerParameters) {
            if (_shellSettings.Name != ShellSettings.DefaultName || !Services.Authorizer.Authorize(StandardPermissions.SiteOwner, T("Not authorized to add sources")))
                return new HttpUnauthorizedResult();

            Pager pager = new Pager(Services.WorkContext.CurrentSite, pagerParameters);

            if (!_packagingSourceManager.GetSources().Any()) {
                Services.Notifier.Error(T("No Gallery feed configured"));
                return View(view, new PackagingListViewModel { Entries = new List<UpdatePackageEntry>() });
            }

            // Get status from background task state or directly
            _backgroundPackageUpdateStatus.Value =
                _backgroundPackageUpdateStatus.Value ??
                _packageUpdateService.GetPackagesStatus(_packagingSourceManager.GetSources());

            foreach (var error in _backgroundPackageUpdateStatus.Value.Errors) {
                for (var scan = error; scan != null; scan = scan.InnerException) {
                    Services.Notifier.Warning(T("Package retrieve error: {0}", scan.Message));
                }
            }

            IEnumerable<UpdatePackageEntry> updatedPackages = _backgroundPackageUpdateStatus.Value.Entries
                .Where(updatePackageEntry =>
                    updatePackageEntry.ExtensionsDescriptor.ExtensionType.Equals(extensionType) &&
                    updatePackageEntry.NewVersionToInstall != null)
                .ToList();

            int totalItemCount = updatedPackages.Count();

            if (pager.PageSize != 0) {
                updatedPackages = updatedPackages.Skip((pager.Page - 1) * pager.PageSize).Take(pager.PageSize);
            }

            return View(view, new PackagingListViewModel {
                LastUpdateCheckUtc = _backgroundPackageUpdateStatus.Value.DateTimeUtc,
                Entries = updatedPackages,
                Pager = Shape.Pager(pager).TotalItemCount(totalItemCount)
            });
        }
    }
}

Lombiq/src/Orchard.Web/Modules/Orchard.Packaging/Controllers/PackagingServicesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Xml.Linq;
using NuGet;
using Orchard.Environment.Configuration;
using Orchard.Environment.Extensions.Models;
using Orchard.FileSystems.AppData;
using Orchard.Localization;
using Orchard.Modules.Services;
using Orchard.Mvc.Extensions;
using Orchard.Packaging.Extensions;
using Orchard.Packaging.Services;
using Orchard.Packaging.ViewModels;
using Orchard.Recipes.Models;
using Orchard.Recipes.Services;
using Orchard.Security;
using Orchard.Themes;
using Orchard.UI.Admin;
using Orchard.UI.Notify;
using IPackageManager = Orchard.Packaging.Services.IPackageManager;
using PackageBuilder = Orchard.Packaging.Services.PackageBuilder;

namespace Orchard.Packaging.Controllers {
    [Themed, Admin]
    public class PackagingServicesController : Controller {

        private readonly ShellSettings _shellSettings;
        private readonly IPackageManager _packageManager;
        private readonly IPackagingSourceManager _packagingSourceManager;
        private readonly IAppDataFolderRoot _appDataFolderRoot;
        private readonly IModuleService _moduleService;
        private readonly IRecipeHarvester _recipeHarvester;
        private readonly IRecipeManager _recipeManager;

        public PackagingServicesController(
            ShellSettings shellSettings,
            IPackageManager packageManager,
            IPackagingSourceManager packagingSourceManager,
            IAppDataFolderRoot appDataFolderRoot,
            IOrchardServices services,
            IModuleService moduleService)
            : this(shellSettings, packageManager, packagingSourceManager, appDataFolderRoot, services, moduleService, null, null) {
        }

        public PackagingServicesController(
            ShellSettings shellSettings,
            IPackageManager packageManager,
            IPackagingSourceManager packagingSourceManager,
            IAppDataFolderRoot appDataFolderRoot,
            IOrchardServices services,
            IModuleService moduleService,
            IRecipeHarvester recipeHarvester,
            IRecipeManager recipeManager) {

            _shellSettings = shellSettings;
            _packageManager = packageManager;
            _appDataFolderRoot = appDataFolderRoot;
            _moduleService = moduleService;
            _recipeHarvester = recipeHarvester;
            _recipeManager = recipeManager;
            _packagingSourceManager = packagingSourceManager;
            Services = services;

            T = NullLocalizer.Instance;
            Logger = Logging.NullLogger.Instance;
        }

        public Localizer T { get; set; }
        public IOrchardServices Services { get; set; }
        public Logging.ILogger Logger { get; set; }

        public ActionResult AddTheme(string returnUrl) {
            if (_shellSettings.Name != ShellSettings.DefaultName || !Services.Authorizer.Authorize(StandardPermissions.SiteOwner, T("Not authorized to add themes")))
                return new HttpUnauthorizedResult();

            return View();
        }

        [HttpPost, ActionName("RemoveTheme")]
        public ActionResult RemoveThemePOST(string themeId, string returnUrl, string retryUrl) {
            if (_shellSettings.Name != ShellSettings.DefaultName || !Services.Authorizer.Authorize(StandardPermissions.SiteOwner, T("Not authorized to remove themes")))
                return new HttpUnauthorizedResult();

            return UninstallPackage(PackageBuilder.BuildPackageId(themeId, DefaultExtensionTypes.Theme), returnUrl, retryUrl);
        }

        public ActionResult AddModule(string returnUrl) {
            if (_shellSettings.Name != ShellSettings.DefaultName || !Services.Authorizer.Authorize(StandardPermissions.SiteOwner, T("Not authorized to add modules")))
                return new HttpUnauthorizedResult();

            return View();
        }

        public ActionResult InstallGallery(string packageId, string version, int sourceId, string redirectUrl) {
            if (_shellSettings.Name != ShellSettings.DefaultName || !Services.Authorizer.Authorize(StandardPermissions.SiteOwner, T("Not authorized to add sources")))
                return new HttpUnauthorizedResult();

            var source = _packagingSourceManager.GetSources().FirstOrDefault(s => s.Id == sourceId);
            if (source == null) {
                return HttpNotFound();
            }

           try {
                PackageInfo packageInfo = _packageManager.Install(packageId, version, source.FeedUrl, HostingEnvironment.MapPath("~/"));

                if (DefaultExtensionTypes.IsTheme(packageInfo.ExtensionType)) {
                    Services.Notifier.Information(T("The theme has been successfully installed. It can be enabled in the \"Themes\" page accessible from the menu."));
                } 
                else if (DefaultExtensionTypes.IsModule(packageInfo.ExtensionType)) {
                    Services.Notifier.Information(T("The module has been successfully installed."));

                    IPackageRepository packageRepository = PackageRepositoryFactory.Default.CreateRepository(new PackageSource(source.FeedUrl, "Default"));
                    IPackage package = packageRepository.FindPackage(packageId);
                    ExtensionDescriptor extensionDescriptor = package.GetExtensionDescriptor(packageInfo.ExtensionType);

                    return InstallPackageDetails(extensionDescriptor, redirectUrl);
                }
            }
           catch (OrchardException e) {
               Services.Notifier.Error(T("Package installation failed: {0}", e.Message));
               return View("InstallPackageFailed");
           }
           catch (Exception) {
               Services.Notifier.Error(T("Package installation failed."));
               return View("InstallPackageFailed");
           }   

           return Redirect(redirectUrl);
        }

        public ActionResult InstallLocally(string redirectUrl) {
            if (_shellSettings.Name != ShellSettings.DefaultName || !Services.Authorizer.Authorize(StandardPermissions.SiteOwner, T("Not authorized to install packages")))
                return new HttpUnauthorizedResult();

            var httpPostedFileBase = Request.Files.Get(0);
            if (httpPostedFileBase == null 
                || Request.Files.Count == 0 
                || string.IsNullOrWhiteSpace(httpPostedFileBase.FileName)) {

                throw new OrchardException(T("Select a file to upload."));
            }
            try {
                string fullFileName = Path.Combine(_appDataFolderRoot.RootFolder, Path.GetFileName(httpPostedFileBase.FileName)).Replace(Path.DirectorySeparatorChar, '/');
                httpPostedFileBase.SaveAs(fullFileName);
                var package = new ZipPackage(fullFileName);
                PackageInfo packageInfo = _packageManager.Install(package, _appDataFolderRoot.RootFolder, HostingEnvironment.MapPath("~/"));
                ExtensionDescriptor extensionDescriptor = package.GetExtensionDescriptor(packageInfo.ExtensionType);
                System.IO.File.Delete(fullFileName);

                if (DefaultExtensionTypes.IsTheme(extensionDescriptor.ExtensionType)) {
                    Services.Notifier.Information(T("The theme has been successfully installed. It can be enabled in the \"Themes\" page accessible from the menu."));
                }
                else if (DefaultExtensionTypes.IsModule(extensionDescriptor.ExtensionType)) {
                    Services.Notifier.Information(T("The module has been successfully installed."));

                    return InstallPackageDetails(extensionDescriptor, redirectUrl);
                }
            }
            catch (OrchardException e) {
                Services.Notifier.Error(T("Package uploading and installation failed: ", e.Message));
                return View("InstallPackageFailed");
            }
            catch (Exception) {
                Services.Notifier.Error(T("Package uploading and installation failed."));
                return View("InstallPackageFailed");
            }

            return Redirect(redirectUrl);
        }

        private ActionResult InstallPackageDetails(ExtensionDescriptor extensionDescriptor, string redirectUrl) {
            if (DefaultExtensionTypes.IsModule(extensionDescriptor.ExtensionType)) {
                List<PackagingInstallFeatureViewModel> features = extensionDescriptor.Features
                    .Where(featureDescriptor => !DefaultExtensionTypes.IsTheme(featureDescriptor.Extension.ExtensionType))
                    .Select(featureDescriptor => new PackagingInstallFeatureViewModel {
                        Enable = true, // by default all features are enabled
                        FeatureDescriptor = featureDescriptor
                    }).ToList();

                List<PackagingInstallRecipeViewModel> recipes = null;
                if (_recipeHarvester != null) {
                    recipes = _recipeHarvester.HarvestRecipes(extensionDescriptor.Id)
                        .Select(recipe => new PackagingInstallRecipeViewModel {
                            Execute = false, // by default no recipes are executed
                            Recipe = recipe
                        }).ToList();
                }

                if (features.Count > 0) {
                    return View("InstallModuleDetails", new PackagingInstallViewModel {
                        Features = features,
                        Recipes = recipes,
                        ExtensionDescriptor = extensionDescriptor
                    });
                }
            }

            return Redirect(redirectUrl);
        }

        [HttpPost, ActionName("InstallPackageDetails")]
        public ActionResult InstallPackageDetailsPOST(PackagingInstallViewModel packagingInstallViewModel, string redirectUrl) {

Lombiq/src/Orchard.Web/Modules/Orchard.Packaging/Views/GalleryUpdates/ModulesUpdates.cshtml
@using Orchard.Modules.Extensions
@using Orchard.Mvc.Html;
@using Orchard.Packaging.ViewModels;
@using Orchard.Packaging.Services;
@using Orchard.Packaging.Models;
@using Orchard.Environment.Extensions.Models;
@using Orchard.Utility.Extensions;
@model PackagingListViewModel

@{
    Style.Require("PackagingAdmin");

    Layout.Title = T("Modules").ToString();
}

@functions {
    public string InstallAction(PackagingEntry package) {
        return Url.Action("InstallGallery", "PackagingServices", new {
            area = "Orchard.Packaging",
            packageId = package.PackageId,
            version = package.Version,
            sourceId = package.Source.Id,
            redirectUrl = HttpContext.Current.Request.RawUrl
        });
    }
}

<fieldset class="update-actions">
    <a class="button" href="@Url.Action("ReloadUpdates", new { returnUrl = ViewContext.RequestContext.HttpContext.Request.ToUrlString()})" title="@T("Most recent check for updates: {0}", Model.LastUpdateCheckUtc == null ? T("Unknown") : Display.DateTimeRelative(dateTimeUtc: Model.LastUpdateCheckUtc.Value))">@T("Check for Updates")</a>
</fieldset>

@if (Model.Entries.Count() <= 0) {
    <p>@T("No module updates available.").ToString()</p>
} else {
    <ul class="contentItems">
    @foreach (var module in Model.Entries) {
        <li>
            @{
                string iconUrl = module.NewVersionToInstall.IconUrl;
                if (string.IsNullOrWhiteSpace(iconUrl)) {
                    iconUrl = Href("../../Content/Images/ModuleDefaultIcon.png");
                }
            }

            <div class="iconThumbnail">
                <div class="extensionDetails column">
                    <div class="extensionName">
                        @if (!string.IsNullOrWhiteSpace(module.NewVersionToInstall.GalleryDetailsUrl)) {
                            <a href="@module.NewVersionToInstall.GalleryDetailsUrl">
                                <h2>@module.NewVersionToInstall.Title<span> - @T("Version: {0}", module.NewVersionToInstall.Version)</span></h2>
                            </a>
                        } else {
                            <h2>@module.NewVersionToInstall.Title<span> - @T("Version: {0}", module.NewVersionToInstall.Version)</span></h2>
                        }
                    </div>

                    <div class="related">
                        @Html.Link(T("Install Latest").Text, InstallAction(module.NewVersionToInstall))@T(" | ")
                        <a href="@module.NewVersionToInstall.PackageStreamUri">@T("Download")</a>
                    </div>

                    <div class="properties">
                        <p>@(module.NewVersionToInstall.Description == null ? T("(No description").Text : module.NewVersionToInstall.Description)</p>
                        <ul class="pageStatus">
                            <li>@T("Last Updated: {0}", module.NewVersionToInstall.LastUpdated)</li>
                            <li>&nbsp;&#124;&nbsp;@T("Author: {0}", !string.IsNullOrEmpty(module.NewVersionToInstall.Authors) ? module.NewVersionToInstall.Authors : T("Unknown").ToString())</li>
                            <li>&nbsp;&#124;&nbsp;@T("Downloads: {0}", module.NewVersionToInstall.DownloadCount)</li>
                            <li>&nbsp;&#124;&nbsp;@T("Website: ")
                                @if (!string.IsNullOrEmpty(module.NewVersionToInstall.ProjectUrl)) { <a href="@module.NewVersionToInstall.ProjectUrl">@module.NewVersionToInstall.ProjectUrl</a> } else { @T("Unknown").ToString() }
                            </li>
                            <li><div>&nbsp;&#124;&nbsp;@T("Rating: ")
                                    <div class="ratings" style="width:@(15 * 5)px" title="@T("Rating: {0} out of 5 ({1} total).", module.NewVersionToInstall.Rating, module.NewVersionToInstall.RatingsCount)">
                                        <div class="score" style="width:@(15 * (module.NewVersionToInstall.Rating))px">&nbsp;</div>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>

                <div class="extensionThumbnail column">
                    <img src="@iconUrl" class="thumbnail" alt="module" />
                </div>
            </div>
        </li>}
    </ul>

    @Display(Model.Pager)
}

Lombiq/src/Orchard.Web/Modules/Orchard.Packaging/Views/GalleryUpdates/ThemesUpdates.cshtml
@using Orchard.Modules.Extensions
@using Orchard.Mvc.Html;
@using Orchard.Packaging.ViewModels;
@using Orchard.Packaging.Services;
@using Orchard.Packaging.Models;
@using Orchard.Environment.Extensions.Models;
@using Orchard.Utility.Extensions;
@model PackagingListViewModel

@{
    Style.Require("PackagingAdmin");

    Layout.Title = T("Themes").ToString();
}

@functions {
    public string InstallAction(PackagingEntry package) {
        return Url.Action("InstallGallery", "PackagingServices", new {
            area = "Orchard.Packaging",
            packageId = package.PackageId,
            version = package.Version,
            sourceId = package.Source.Id,
            redirectUrl = HttpContext.Current.Request.RawUrl
        });
    }
}

<fieldset class="update-actions">
    <a class="button" href="@Url.Action("ReloadUpdates", new { returnUrl = ViewContext.RequestContext.HttpContext.Request.ToUrlString()})" title="@T("Most recent check for updates: {0}", Model.LastUpdateCheckUtc == null ? T("Unknown") : Display.DateTimeRelative(dateTimeUtc: Model.LastUpdateCheckUtc.Value))" >@T("Check for Updates")</a>
</fieldset>

@if (Model.Entries.Count() <= 0) {
    <p>@T("No theme updates available.").ToString()</p>
} else {
    <ul class="contentItems theme">
    @foreach (var theme in Model.Entries) {
        <li>
            @{
                string extensionClass = "iconThumbnail";
                string iconUrl = theme.NewVersionToInstall.IconUrl;
                if (!string.IsNullOrWhiteSpace(@theme.NewVersionToInstall.FirstScreenshot)) {
                    iconUrl = theme.NewVersionToInstall.FirstScreenshot;
                    extensionClass = "screenshotThumbnail";
                } else if (string.IsNullOrWhiteSpace(iconUrl)) {
                    iconUrl = Href("../../Content/Images/imagePlaceholder.png");
                    extensionClass = "screenshotThumbnail";
                }
            }

            <div class="@extensionClass">
                <div class="extensionDetails column">
                    <div class="extensionName">
                        @if (!string.IsNullOrWhiteSpace(theme.NewVersionToInstall.GalleryDetailsUrl)) {
                            <a href="@theme.NewVersionToInstall.GalleryDetailsUrl">
                                <h2>@theme.NewVersionToInstall.Title<span> - @T("Version: {0}", theme.NewVersionToInstall.Version)</span></h2>
                            </a>
                        } else {
                            <h2>@theme.NewVersionToInstall.Title<span> - @T("Version: {0}", theme.NewVersionToInstall.Version)</span></h2>
                        }
                    </div>

                    <div class="related">
                        @Html.Link(T("Install Latest").Text, InstallAction(theme.NewVersionToInstall))@T(" | ")
                        <a href="@theme.NewVersionToInstall.PackageStreamUri">@T("Download")</a>
                    </div>

                    <div class="properties">
                        <p>@(theme.NewVersionToInstall.Description == null ? T("(No description").Text : theme.NewVersionToInstall.Description)</p>
                        <ul class="pageStatus">
                            <li>@T("Last Updated: {0}", theme.NewVersionToInstall.LastUpdated)</li>
                            <li>&nbsp;&#124;&nbsp;@T("Author: {0}", !string.IsNullOrEmpty(theme.NewVersionToInstall.Authors) ? theme.NewVersionToInstall.Authors : T("Unknown").ToString())</li>
                            <li>&nbsp;&#124;&nbsp;@T("Downloads: {0}", theme.NewVersionToInstall.DownloadCount)</li>
                            <li>&nbsp;&#124;&nbsp;@T("Website: ")
                                @if (!string.IsNullOrEmpty(theme.NewVersionToInstall.ProjectUrl)) { <a href="@theme.NewVersionToInstall.ProjectUrl">@theme.NewVersionToInstall.ProjectUrl</a> } else { @T("Unknown").ToString() }
                            </li>
                            <li><div>&nbsp;&#124;&nbsp;@T("Rating: ")
                                    <div class="ratings" style="width:@(15 * 5)px" title="@T("Rating: {0} out of 5 ({1} total).", theme.NewVersionToInstall.Rating, theme.NewVersionToInstall.RatingsCount)">
                                        <div class="score" style="width:@(15 * (theme.NewVersionToInstall.Rating))px">&nbsp;</div>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>

                <div class="extensionThumbnail column">
                    <img src="@iconUrl" class="thumbnail" alt="theme" />
                </div>
            </div>
        </li>}
    </ul>

    @Display(Model.Pager)
}